### ISSUE TITLE
Error during building 

### ISSUE THREAD

**Issue by mikhno-s** [Arman92/go-tdlib#34] opened 2020-01-27 15:45 UTC
Hi

I try to build my go app with your *awesome* lib on raspberry 3b

Previously, I successfully did it on my laptop. Now, I build tdlib on raspberry, put all compiled things to /usr/local/
```shell
$ ls /usr/local/include/td/*
/usr/local/include/td/telegram:
Client.h  Log.h  td_api.h  td_api.hpp  td_json_client.h  td_log.h  tdjson_export.h

/usr/local/include/td/tl:
TlObject.h

$ ls /usr/local/lib/
cmake         libtdclient.a  libtddb.a     libtdjson.so.1.5.0   libtdjson_static.a  libtdsqlite.a  python2.7
libtdactor.a  libtdcore.a    libtdjson.so  libtdjson_private.a  libtdnet.a          libtdutils.a   python3.7```

```

But when I tried to build my app - I got a lot of errors

They are all about `undefined reference`, like 

```
...
/usr/bin/ld: mtproto_api.cpp:(.text._ZNK2td11mtproto_api17p_q_inner_data_dc5storeERNS_16TlStorerToStringEPKc+0x78): undefined reference to `std::__1
::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
/usr/bin/ld: mtproto_api.cpp:(.text._ZNK2td11mtproto_api17p_q_inner_data_dc5storeERNS_16TlStorerToStringEPKc+0x88): undefined reference to `std::__1
::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
...
/usr/bin/ld: mtproto_api.cpp:(.text._ZNK2td11mtproto_api17p_q_inner_data_dc5storeERNS_16TlStorerToStringEPKc+0x27c): undefined reference to `std::__
1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
/usr/bin/ld: mtproto_api.cpp:(.text._ZNK2td11mtproto_api17p_q_inner_data_dc5storeERNS_16TlStorerToStringEPKc+0x2a0): undefined reference to `std::__
1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: mtproto_api.cpp:(.text._ZNK2td11mtproto_api17p_q_inner_data_dc5storeERNS_16TlStorerToStringEPKc+0x2c0): undefined reference to `std::__
1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
...
utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x24): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x5c): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x7c): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0x90): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0xa0): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)'
/usr/bin/ld: /usr/local/lib/libtdutils.a(utf8.cpp.o):utf8.cpp:(.text._ZN2td21append_utf8_characterERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEj+0xb4): more undefined references to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)' follow
collect2: error: ld returned 1 exit status
```
 
And so on, and so on..

What I did wrong? Is there an issue with static/dynamic compiling of source tdlib?
Have you try to build your apps using your lib on arm?

Let me know, if you know, what can be the cause of errors.
Thanks a lot!

UPDATE:
```
go version go1.11.6 linux/arm
Linux raspberrypi 4.19.93-v7+ #1290 SMP Fri Jan 10 16:39:50 GMT 2020 armv7l GNU/Linux
```

**Comment by Arman92** [comment] 2021-06-04 21:35
Hello @mikhno-s, sorry for super late reply, the problem is that [TDLib build instructions](https://tdlib.github.io/td/build.html?language=Go) has been changed since last update on the repo.

They are now using LLVM C++ instead of GNU libstdc++. so instead of linking against `-lstdc++`. one should link with `-lc++` instead.

It's fixed on the master branch now.

**Closed by Arman92** 2021-06-04 21:35 UTC
